-- PostGIS quando disponível; segue sem geometria se a extensão não estiver instalada.
DO $$
BEGIN
    CREATE EXTENSION IF NOT EXISTS postgis;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'PostGIS indisponivel; prosseguindo sem suporte geografico.';
END
$$;

-- Fonte de dados (portal ou imobiliária)
CREATE TABLE source (
    source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    base_url VARCHAR(2000),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_source_code UNIQUE (code)
);

-- Execução de coleta
CREATE TABLE crawl_run (
    crawl_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES source (source_id),
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    listings_seen INTEGER NOT NULL DEFAULT 0,
    observations_created INTEGER NOT NULL DEFAULT 0,
    events_created INTEGER NOT NULL DEFAULT 0,
    errors INTEGER NOT NULL DEFAULT 0,
    extractor_version VARCHAR(64),
    message TEXT
);

CREATE INDEX idx_crawl_run_source ON crawl_run (source_id);

-- Identidade estável do anúncio naquela fonte
CREATE TABLE source_listing (
    source_listing_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES source (source_id),
    external_id VARCHAR(64) NOT NULL,
    url VARCHAR(2000),
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_source_listing UNIQUE (source_id, external_id)
);

CREATE INDEX idx_source_listing_source ON source_listing (source_id);

-- Estado observado (append-only); nova linha somente quando o conteúdo muda
CREATE TABLE listing_observation (
    listing_observation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_listing_id BIGINT NOT NULL REFERENCES source_listing (source_listing_id),
    crawl_run_id BIGINT REFERENCES crawl_run (crawl_run_id),
    observed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    title VARCHAR(4000),
    extra VARCHAR(4000),
    price NUMERIC(15, 2),
    price_text VARCHAR(255),
    city VARCHAR(255),
    neighborhood VARCHAR(255),
    type VARCHAR(255),
    image_url VARCHAR(2000),
    content_hash VARCHAR(64) NOT NULL
);

CREATE INDEX idx_observation_listing ON listing_observation (source_listing_id);

CREATE INDEX idx_observation_run ON listing_observation (crawl_run_id);

-- Eventos de mudança idempotentes
CREATE TABLE listing_event (
    listing_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_listing_id BIGINT NOT NULL REFERENCES source_listing (source_listing_id),
    crawl_run_id BIGINT REFERENCES crawl_run (crawl_run_id),
    event_type VARCHAR(32) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    old_price NUMERIC(15, 2),
    new_price NUMERIC(15, 2),
    dedup_key VARCHAR(200) NOT NULL,
    CONSTRAINT uq_listing_event_dedup UNIQUE (dedup_key)
);

CREATE INDEX idx_event_listing ON listing_event (source_listing_id);

INSERT INTO
    source (code, name, base_url)
VALUES (
        'IMOVEIS-SC',
        'Imóveis SC',
        'https://www.imoveis-sc.com.br'
    ),
    (
        'ACRC',
        'ACRC Imóveis',
        'https://www.acrcimoveis.com.br'
    ),
    (
        'ZAP-IMOVEIS',
        'ZAP Imóveis',
        'https://www.zapimoveis.com.br'
    );