-- Projeção de estado corrente para leitura rápida (nunca apagada; substitui o antigo deleteAll+saveAll)
CREATE TABLE imovel (
    imovel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_listing_id BIGINT REFERENCES source_listing (source_listing_id),
    external_id VARCHAR(64),
    titulo VARCHAR(4000),
    extra VARCHAR(4000),
    price NUMERIC(15, 2),
    origem VARCHAR(255),
    price_varchar VARCHAR(4000),
    link VARCHAR(4000),
    image VARCHAR(4000),
    city VARCHAR(255),
    neighborhood VARCHAR(255),
    type VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    first_seen_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    CONSTRAINT uq_imovel_source_listing UNIQUE (source_listing_id)
);

CREATE INDEX idx_imovel_city ON imovel (city);

CREATE INDEX idx_imovel_origem ON imovel (origem);