-- Normaliza os tipos historicos da projecao para o conjunto canonico
-- (Apartamento, Casa, Sobrado, Terreno, Comercial, Rural, Outro).
-- Novas coletas ja gravam o tipo normalizado via PropertyTypeNormalizer.
UPDATE imovel
SET
    type = CASE lower(
            regexp_replace(btrim (type), '\s+', ' ', 'g')
        )
        WHEN 'apartamento' THEN 'Apartamento'
        WHEN 'apartamentos' THEN 'Apartamento'
        WHEN 'apto' THEN 'Apartamento'
        WHEN 'kitnet' THEN 'Apartamento'
        WHEN 'studio' THEN 'Apartamento'
        WHEN 'cobertura' THEN 'Apartamento'
        WHEN 'flat' THEN 'Apartamento'
        WHEN 'loft' THEN 'Apartamento'
        WHEN 'casa' THEN 'Casa'
        WHEN 'casas' THEN 'Casa'
        WHEN 'casa geminada' THEN 'Casa'
        WHEN 'geminada' THEN 'Casa'
        WHEN 'sobrado' THEN 'Sobrado'
        WHEN 'sobrados' THEN 'Sobrado'
        WHEN 'terreno' THEN 'Terreno'
        WHEN 'terrenos' THEN 'Terreno'
        WHEN 'lote' THEN 'Terreno'
        WHEN 'lotes' THEN 'Terreno'
        WHEN 'lote terreno' THEN 'Terreno'
        WHEN 'comercial' THEN 'Comercial'
        WHEN 'sala' THEN 'Comercial'
        WHEN 'salas' THEN 'Comercial'
        WHEN 'sala comercial' THEN 'Comercial'
        WHEN 'conjunto comercial' THEN 'Comercial'
        WHEN 'loja' THEN 'Comercial'
        WHEN 'lojas' THEN 'Comercial'
        WHEN 'ponto' THEN 'Comercial'
        WHEN 'ponto comercial' THEN 'Comercial'
        WHEN 'galpao' THEN 'Comercial'
        WHEN 'galpão' THEN 'Comercial'
        WHEN 'galpoes' THEN 'Comercial'
        WHEN 'barracao' THEN 'Comercial'
        WHEN 'barracão' THEN 'Comercial'
        WHEN 'pavilhao' THEN 'Comercial'
        WHEN 'pavilhão' THEN 'Comercial'
        WHEN 'deposito' THEN 'Comercial'
        WHEN 'depósito' THEN 'Comercial'
        WHEN 'box' THEN 'Comercial'
        WHEN 'garagem' THEN 'Comercial'
        WHEN 'hotel' THEN 'Comercial'
        WHEN 'edificio comercial' THEN 'Comercial'
        WHEN 'edifício comercial' THEN 'Comercial'
        WHEN 'predio comercial' THEN 'Comercial'
        WHEN 'prédio comercial' THEN 'Comercial'
        WHEN 'predio' THEN 'Comercial'
        WHEN 'prédio' THEN 'Comercial'
        WHEN 'predios' THEN 'Comercial'
        WHEN 'predio residencial' THEN 'Comercial'
        WHEN 'prédio residencial' THEN 'Comercial'
        WHEN 'chacara' THEN 'Rural'
        WHEN 'chácara' THEN 'Rural'
        WHEN 'chacaras' THEN 'Rural'
        WHEN 'fazenda' THEN 'Rural'
        WHEN 'fazendas' THEN 'Rural'
        WHEN 'sitio' THEN 'Rural'
        WHEN 'sítio' THEN 'Rural'
        WHEN 'sitios' THEN 'Rural'
        WHEN 'rural' THEN 'Rural'
        WHEN 'area rural' THEN 'Rural'
        WHEN 'área rural' THEN 'Rural'
        WHEN 'terreno rural' THEN 'Rural'
        ELSE 'Outro'
    END
WHERE
    type IS NOT NULL
    AND btrim (type) <> '';