name: Docker CI Pipeline for Java Project

# Trigger the workflow when a pull request is opened or updated
on:
  pull_request:
    branches:
      - main
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional but recommended for advanced Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t java-test-app .

      # Step 4: Run the Docker container and execute Maven commands
      - name: Run tests in Docker container
        run: docker run --rm java-test-app
